
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8781

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: za-ribbon-consumer
    api-b:
      path: /api-b/**
      serviceId: za-feign-consumer
    api-sc:
          path: /api-sc/**
          serviceId: za-sidecar